# CircleCI

# Version CircleCI
version: 2.1
# Default configuration
defaults: &defaults
  working_directory: ~/app # Working_directory: ~/app
  # Docker image that will be used
  docker:
    - image: cimg/python:3.11 # Python 3.11
# Jobs that will be executed
jobs:
  # Job name
  app-build:
    # Default configuration
    <<: *defaults
    # Steps that will be executed
    steps:
      # Checkout the code from the repository
      - checkout
      # Install package python3-pip for install dependencies
      # Create virtual environment for python3
      # Install dependencies with pip of requirements.txt
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip
            pip install --upgrade pip
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      # Save the virtual environment for the next job for persisting data
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  # Job name
  app-tests:
    # Default configuration
    <<: *defaults
    # Steps that will be executed
    steps:
      # Attach the workspace from the previous job for persisting data
      - attach_workspace:
          at: ~/app
      - run:
          name: Run tests
          command: |
            # Source env
            source env/bin/activate
            # Run linter pylint to check code of app calculator.py
            pylint src/calculator.py
      # Run test coverage with pytest
      - run:
          name: Run tests pytest coverage
          command: |
            # Source env
            source env/bin/activate
            # Run test coverage with pytest
            coverage run -m pytest tests/test_calculator.py
            python3 -m pytest --cov=src
      # Run test with pytest
      - run:
          name: Run tests pytest
          command: |
            # Source env
            source env/bin/activate
            # Run test with pytest
            python3 -m pytest
            # Create directorys for test results
            mkdir docs-test-reports
            # Generate report html of test results
            python3 -m pytest --html=./docs-tests-reports/report.html
            # Create directorys for test results
            mkdir docs-test
            # Generate report xml of test results
            python3 -m pytest --junitxml=./docs-tests/report.xml
      # Generate artifacts of test results
      - store_test_results:
          path: docs-tests/report.xml
      - store_artifacts:
          path: docs-tests-reports
          destination: docs-tests-reports
  # Job name
  app-docs:
    # Default configuration
    <<: *defaults
    # Steps that will be executed
    steps:
      # Attach the workspace from the previous job for persisting data
      - attach_workspace:
          at: ~/app
      - run:
          name: Generate documentation
          command: |
            # Create directorys for documentation of code app
            mkdir docs-html
            # Source env
            source env/bin/activate
            # Generate documentation of code app with pdoc
            pdoc src/calculator.py -o ./docs-html
      # Generate artifacts of documentation
      - store_artifacts:
          path: docs-html
          destination: docs-html
  # Job name
  app-deploy:
    # Default configuration
    <<: *defaults
    # Steps that will be executed
    steps:
      # Attach the workspace from the previous job for persisting data
      - attach_workspace:
          at: ~/app
      - run:
          name: Build package
          command: |
            # Source env
            source env/bin/activate
            # Build package app
            pip install build
            python3 -m build
# Workflows that will be executed
workflows:
  # Workflow name
  app-build-tests-docs-deploy:
    # Jobs that will be executed
    jobs:
      # Job name
      - app-build
      - app-tests:
          requires:
            - app-build
      - app-docs:
          requires:
            - app-tests
      - app-deploy:
          requires:
            - app-build
            - app-tests
            - app-docs
          filters:
            branches:
              only:
                - main
