# CircleCI

# Version CircleCI
version: 2.1
# Default configuration
defaults: &defaults
  working_directory: ~/app # Working_directory: ~/app
  # Docker image that will be used
  docker:
    - image: cimg/python:3.11 # Python 3.11
# Jobs that will be executed
jobs:
  # Job name
  test-app:
    # Default configuration
    <<: *defaults
    # Steps that will be executed
    steps:
      # Checkout the code from the repository
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      # Run linter pylint
      - run:
          name: Run linter pylint
          command: |
            pylint src/calculator.py
      # Run test coverage with pytest
      - run:
          name: Run tests pytest coverage
          command: |
            coverage run -m pytest tests/test_calculator.py
            python3 -m pytest --cov=src
      # Run test with pytest
      - run:
          name: Run tests pytest
          command: |
            python3 -m pytest
            # Generate report html of test results
            python3 -m pytest --html=report.html
# Workflows that will be executed
workflows:
  # Workflow name
  test-app-deploy:
    # Jobs that will be executed
    jobs:
      # Job name
      - test-app
