# CircleCI

# Version CircleCI
version: 2.1
# Jobs that will be executed
jobs:
  # Job name
  test-app:
    # Docker image
    docker:
      - image: cimg/python:3.11 # Python 3.11
    # Directory where the code will be executed
    working_directory: ~/app
    # Steps that will be executed
    steps:
      # Checkout the code from the repository
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      # Run linter pylint and flake8
      - run:
          name: Run linter
          command: |
            pylint calculator
            flake8 --exclude=venv* --statistics
      # Run test coverage with pytest
      - run:
          name: Run tests
          command: |
            pytest -v --cov=calculator
# Workflows that will be executed
workflows:
  # Workflow name
  test-app-deploy:
    # Jobs that will be executed
    jobs:
      # Job name
      - test-app
