apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pycalculator
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pycalc
    repoURL: https://rafatorices.github.io/example_helm_pycalculator/
    targetRevision: "0.1.0"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
