apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pycalculator
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pycalc # Name of the chart that appears in the readme helm chart repository
    repoURL: https://rafatorices.github.io/example_helm_pycalculator/ # URL of the helm chart repository
    targetRevision: "0.1.0" # Version of the helm chart that appears in the index.yaml file of the helm chart repository
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
