apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pycalculator
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: app
    repoURL: https://github.com/RafaTorices/example_helm_pycalculator
    targetRevision: "1.16.0"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
